const dishes = [
    {
      _id: 'drinks01',
      name: 'Bloody Mary',
      image: '/images/drinks01.png',
      ingredients:
        'Vodka, Chanh tươi',
      category: 'dr',
      price: 59.000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'drinks02',
      name: 'Blue Lagoon',
      image: '/images/drinks02.png',
      ingredients:
        'Martini. Rhum, Chanh tươi',
      category: 'dr',
      price: 59.000,
      countInStock: 7,
      rating: 4.0,
      numReviews: 8,
      mon_an_kem: [],
    },
    {
      _id: 'drinks03',
      name: 'Blur Mad',
      image: '/images/drinks03.png',
      ingredients:
        'Gin, Sherry, nho đen, chanh tươi',
      category: 'dr',
      price: 79.000,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'drinks04',
      name: 'Campari Orange Cocktail',
      image: '/images/drinks04.png',
      ingredients:
        'Hennessy, Rhum, cam',
      category: 'dr',
      price: 49.000,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'drinks05',
      name: 'Lemintade',
      image: '/images/drinks05.png',
      ingredients:
        'Chanh tươi, bạc hà',
      category: 'dr',
      price: 59.000,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
      mon_an_kem: [],
    },
    {
      _id: 'drinks06',
      name: 'Margiata',
      image: '/images/drinks06.png',
      ingredients:
        'Chanh, Rhum, Vodka',
      category: 'dr',
      price: 49.000,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'drinks07',
      name: 'Expresso',
      image: '/images/drinks07.png',
      ingredients:
        'Cafein',
      category: 'dr',
      price: 29.000,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'drinks08',
      name: 'Pinacole',
      image: '/images/drinks08.png',
      ingredients:
        'Dứa, Rhum, Gin',
      category: 'dr',
      price: 49.000,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
      mon_an_kem: [],
    },

    /*-----------------------------------*/
    {
      _id: 'dessert01',
      name: 'Bánh táo kẹp kem',
      image: '/images/dessert01.png',
      ingredients:
        'Bánh táo, kem tươi',
      category: 'des',
      price: 39.000,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'dessert02',
      name: 'Waffle dâu tằm',
      image: '/images/dessert02.png',
      ingredients:
        'Bánh waffle, dâu tằm, syrup',
      category: 'des',
      price: 49.000,
      countInStock: 10,
      rating: 4.7,
      numReviews: 10,
      mon_an_kem: [],
    },
    {
      _id: 'dessert03',
      name: 'Kem Café Liégois',
      image: '/images/dessert03.png',
      ingredients:
        'Kem, chocolate, bánh quế',
      category: 'des',
      price: 35.000,
      countInStock: 3,
      rating: 4.5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'dessert04',
      name: 'Bánh kem chocolate',
      image: '/images/dessert04.png',
      ingredients:
        'Bánh gato, chocolate',
      category: 'des',
      price: 40.000,
      countInStock: 23,
      rating: 4,
      numReviews: 50,
      mon_an_kem: [],
    },
    {
      _id: 'dessert05',
      name: 'Tiramisu chocolate',
      image: '/images/dessert05.png',
      ingredients:
        'Bánh gato, chocolate',
      category: 'des',
      price: 40.000,
      countInStock: 34,
      rating: 5,
      numReviews: 70,
      mon_an_kem: [],
    },
    {
      _id: 'dessert06',
      name: 'Bánh mì ngọt Mexico',
      image: '/images/dessert06.png',
      ingredients:
        'Bánh mì, sữa',
      category: 'des',
      price: 30.000,
      countInStock: 5,
      rating: 4.5,
      numReviews: 23,
      mon_an_kem: [],
    },
    {
      _id: 'dessert07',
      name: 'Puff kem',
      image: '/images/dessert07.png',
      ingredients:
        'Bánh puff, kem tươi',
      category: 'des',
      price: 20.000,
      countInStock: 7,
      rating: 3.5,
      numReviews: 20,
      mon_an_kem: [],
    },
    {
      _id: 'dessert08',
      name: 'Crème Brùlée',
      image: '/images/dessert08.png',
      ingredients:
        'Custard, caramen',
      category: 'des',
      price: 39.000,
      countInStock: 10,
      rating: 5,
      numReviews: 20,
      mon_an_kem: [],
    },
    {
      _id: 'dessert09',
      name: 'Cupcake chocolate',
      image: '/images/dessert09.png',
      ingredients:
        'Custard, chocolate',
      category: 'des',
      price: 15.000,
      countInStock: 2,
      rating: 4.5,
      numReviews: 20,
      mon_an_kem: [],
    },
    {
      _id: 'dessert10',
      name: 'Cupcake hoa hồng',
      image: '/images/dessert10.png',
      ingredients:
        'Custard, hoa hồng',
      category: 'des',
      price: 15.000,
      countInStock: 4,
      rating: 4.5,
      numReviews: 20,
      mon_an_kem: [],
    },
    {
      _id: 'dessert11',
      name: 'Progiteroles',
      image: '/images/dessert11.png',
      ingredients:
        'Custard, chocolate',
      category: 'des',
      price: 39.000,
      countInStock: 10,
      rating: 5,
      numReviews: 20,
      mon_an_kem: [],
    },
    {
      _id: 'dessert12',
      name: 'Peche Melba',
      image: '/images/dessert12.png',
      ingredients:
        'Dâu tây, kem',
      category: 'des',
      price: 39.000,
      countInStock: 10,
      rating: 5,
      numReviews: 20,
      mon_an_kem: [],
    },

    /*-----------------------------------*/
    {
      _id: 'fastfood01',
      name: 'Hamburger bò nướng',
      image: '/images/fastfood01.png',
      ingredients:
        'Bánh mì, rau xà lách, cà chua, thịt bò nướng',
      category: 'faf',
      price: 25.000,
      countInStock: 12,
      rating: 4.5,
      numReviews: 20,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'fastfood02',
      name: 'Sandwich bò nướng',
      image: '/images/fastfood02.png',
      ingredients:
        'Bánh mì, rau xà lách, cà chua, thịt bò nướng',
      category: 'faf',
      price: 25.000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 23,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'fastfood03',
      name: 'Gà rán giòn cay',
      image: '/images/fastfood03.png',
      ingredients:
        'Gà',
      category: 'faf',
      price: 20.000,
      countInStock: 8,
      rating: 4,
      numReviews: 20,
      mon_an_kem: [],
    },
    {
      _id: 'fastfood04',
      name: 'Cánh gà nướng mật ong',
      image: '/images/fastfood04.png',
      ingredients:
        'Cánh gà, mật ong',
      category: 'faf',
      price: 20.000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 20,
      mon_an_kem: [],
    },
    {
      _id: 'fastfood05',
      name: 'Burger King Whopper',
      image: '/images/fastfood05.png',
      ingredients:
        'Bánh mì, rau xà lách, cà chua, thịt bò nướng',
      category: 'faf',
      price: 25.000,
      countInStock: 15,
      rating: 4,
      numReviews: 20,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'fastfood06',
      name: 'Hotdog',
      image: '/images/fastfood06.png',
      ingredients:
        'Bánh mì, xúc xích nướng',
      category: 'faf',
      price: 20.000,
      countInStock: 5,
      rating: 4,
      numReviews: 14,
      mon_an_kem: [],
    },
    {
      _id: 'fastfood07',
      name: 'Frenchfries',
      image: '/images/fastfood07.png',
      ingredients:
        'Khoai tây',
      category: 'faf',
      price: 10.000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 13,
      mon_an_kem: [],
    },
    {
      _id: 'fastfood08',
      name: 'Hamburger phô mai bò',
      image: '/images/fastfood08.png',
      ingredients:
        'Bánh mì, rau xà lách, cà chua, thịt bò nướng, phô mai',
      category: 'faf',
      price: 45.000,
      countInStock: 4,
      rating: 5,
      numReviews: 30,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'fastfood09',
      name: 'Đùi gà nướng',
      image: '/images/fastfood09.png',
      ingredients:
        'Đùi gà',
      category: 'faf',
      price: 25.000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 23,
      mon_an_kem: [],
    },
    {
      _id: 'fastfood10',
      name: 'Pizza phô mai',
      image: '/images/fastfood10.png',
      ingredients:
        'Phô mai Mozzarella, xúc xích',
      category: 'faf',
      price: 79.000,
      countInStock: 5,
      rating: 4,
      numReviews: 7,
      mon_an_kem: [],
    },
    {
      _id: 'fastfood11',
      name: 'Hamburger doublebeef',
      image: '/images/fastfood11.png',
      ingredients:
        'Bánh mì, rau xà lách, cà chua, thịt bò nướng, phô mai',
      category: 'faf',
      price: 55.000,
      countInStock: 6,
      rating: 4,
      numReviews: 20,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'fastfood12',
      name: 'Hamburger barbecue',
      image: '/images/fastfood12.png',
      ingredients:
        'Bánh mì, rau xà lách, cà chua, thịt nướng, phô mai',
      category: 'faf',
      price: 45.000,
      countInStock: 10,
      rating: 5,
      numReviews: 34,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'fastfood13',
      name: '"Một mớ" gà rán',
      image: '/images/fastfood13.png',
      ingredients:
        'Gà',
      category: 'faf',
      price: 105.000,
      countInStock: 2,
      rating: 3.5,
      numReviews: 30,
      mon_an_kem: [],
    },
    {
      _id: 'fastfood14',
      name: 'Taco',
      image: '/images/fastfood14.png',
      ingredients:
        'Thịt, các loại rau củ, trứng, bánh mì',
      category: 'faf',
      price: 105.000,
      countInStock: 7,
      rating: 3.5,
      numReviews: 30,
      mon_an_kem: [],
    },

    /*-----------------------------------*/
    {
      _id: 'seafood01',
      name: 'Tôm hùm nướng phô mai',
      image: '/images/seafood01.png',
      ingredients:
        'Tôm hùm, phô mai Cheddar',
      category: 'sef',
      price: 625.000,
      countInStock: 15,
      rating: 5,
      numReviews: 20,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'seafood02',
      name: 'Tôm hùm nướng cay',
      image: '/images/seafood02.png',
      ingredients:
        'Tôm hùm, ớt các loại',
      category: 'sef',
      price: 455.000,
      countInStock: 12,
      rating: 4.5,
      numReviews: 22,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'seafood03',
      name: 'Cua hấp',
      image: '/images/seafood03.png',
      ingredients:
        'Cua',
      category: 'sef',
      price: 355.000,
      countInStock: 3,
      rating: 5,
      numReviews: 34,
      mon_an_kem: [],
    },
    {
      _id: 'seafood04',
      name: 'Tổ hợp hải sản',
      image: '/images/seafood04.png',
      ingredients:
        'Cua, tôm, sò',
      category: 'sef',
      price: 700.000,
      countInStock: 12,
      rating: 4,
      numReviews: 26,
      mon_an_kem: [],
    },
    {
      _id: 'seafood05',
      name: 'Cua rang',
      image: '/images/seafood05.png',
      ingredients:
        'Cua, bắp, hành',
      category: 'sef',
      price: 239.000,
      countInStock: 5,
      rating: 3,
      numReviews: 10,
      mon_an_kem: [],
    },
    {
      _id: 'seafood06',
      name: 'Nghêu hấp sả',
      image: '/images/seafood06.png',
      ingredients:
        'Nghêu, sả',
      category: 'sef',
      price: 200.000,
      countInStock: 8,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'seafood07',
      name: 'Tôm hùm hấp',
      image: '/images/seafood07.png',
      ingredients:
        'Tôm hùm',
      category: 'sef',
      price: 900.000,
      countInStock: 3,
      rating: 4.5,
      numReviews: 25,
      mon_an_kem: [],
    },
    {
      _id: 'seafood08',
      name: 'Tôm cua',
      image: '/images/seafood08.png',
      ingredients:
        'Tôm, cua',
      category: 'sef',
      price: 400.000,
      countInStock: 3,
      rating: 4.5,
      numReviews: 10,
      mon_an_kem: [],
    },
    {
      _id: 'seafood09',
      name: 'Ghẹ hấp nước dừa',
      image: '/images/seafood09.png',
      ingredients:
        'Ghẹ, nước dừa',
      category: 'sef',
      price: 200.000,
      countInStock: 8,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'seafood10',
      name: 'Cá lala kho',
      image: '/images/seafood10.png',
      ingredients:
        'Cá lala',
      category: 'sef',
      price: 150.000,
      countInStock: 4,
      rating: 3.5,
      numReviews: 17,
      mon_an_kem: [],
    },
    {
      _id: 'seafood11',
      name: 'Cá shalik nướng',
      image: '/images/seafood11.png',
      ingredients:
        'Cá shalik',
      category: 'sef',
      price: 154.000,
      countInStock: 6,
      rating: 4.5,
      numReviews: 16,
      mon_an_kem: [],
    },
    {
      _id: 'seafood12',
      name: 'Tôm xào chua ngọt',
      image: '/images/seafood12.png',
      ingredients:
        'Tôm, cà chua',
      category: 'sef',
      price: 200.000,
      countInStock: 22,
      rating: 5,
      numReviews: 67,
      mon_an_kem: [],
    },
    {
      _id: 'seafood13',
      name: 'Tôm luộc',
      image: '/images/seafood13.png',
      ingredients:
        'Tôm',
      category: 'sef',
      price: 200.000,
      countInStock: 4,
      rating: 3.5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'seafood14',
      name: 'Cá xaxa hấp',
      image: '/images/seafood14.png',
      ingredients:
        'Cá xaxa',
      category: 'sef',
      price: 200.000,
      countInStock: 8,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'seafood15',
      name: 'Tôm chiên',
      image: '/images/seafood15.png',
      ingredients:
        'Tôm',
      category: 'sef',
      price: 180.000,
      countInStock: 4,
      rating: 5,
      numReviews: 35,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },

    /*---------------------------*/
    {
      _id: 'dimsum01',
      name: 'Dimsum nguyên vị',
      image: '/images/dimsum01.png',
      ingredients:
        'Bột gạo, xá xíu, xíu mại',
      category: 'Dimsum',
      price: 45.000,
      countInStock: 4,
      rating: 5,
      numReviews: 24,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'dimsum02',
      name: 'Dimsum cay',
      image: '/images/dimsum02.png',
      ingredients:
        'Bột gạo, xá xíu, xíu mại, ớt',
      category: 'Dimsum',
      price: 35.000,
      countInStock: 6,
      rating: 3.5,
      numReviews: 2,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'dimsum03',
      name: 'Dimsum tôm',
      image: '/images/dimsum03.png',
      ingredients:
        'Bột gạo, tôm',
      category: 'Dimsum',
      price: 55.000,
      countInStock: 4,
      rating: 5,
      numReviews: 32,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'dimsum04',
      name: 'Dimsum hải sản',
      image: '/images/dimsum04.png',
      ingredients:
        'Bột gạo, tôm, cua, mực',
      category: 'Dimsum',
      price: 45.000,
      countInStock: 7,
      rating: 5,
      numReviews: 35,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },
    {
      _id: 'dimsum05',
      name: 'Dimsum trứng',
      image: '/images/dimsum05.png',
      ingredients:
        'Bột gạo, trứng, đậu cove, rau củ các loại',
      category: 'Dimsum',
      price: 55.000,
      countInStock: 4,
      rating: 5,
      numReviews: 24,
      mon_an_kem: ["Rau trộn", "Kim chi carrot"],
    },

    /*---------------------------*/
    {
      _id: 'salad01',
      name: 'Salad nguyên bản',
      image: '/images/salad01.png',
      ingredients:
        'Rau xà lách, cà chua, giấm đường, dưa leo',
      category: 'Salad',
      price: 45.000,
      countInStock: 4,
      rating: 5,
      numReviews: 24,
      mon_an_kem: [],
    },
    {
      _id: 'salad02',
      name: 'Salad đậu ván',
      image: '/images/salad02.png',
      ingredients:
        'Đậu ván, đậu đỏ',
      category: 'Salad',
      price: 35.000,
      countInStock: 6,
      rating: 3.5,
      numReviews: 2,
      mon_an_kem: [],
    },
    {
      _id: 'salad03',
      name: 'Salad ức gà',
      image: '/images/salad03.png',
      ingredients:
        'Rau các loại, cà chua, ức gà',
      category: 'Salad',
      price: 55.000,
      countInStock: 4,
      rating: 5,
      numReviews: 32,
      mon_an_kem: [],
    },
    {
      _id: 'salad04',
      name: 'Salad cá hồi',
      image: '/images/salad04.png',
      ingredients:
        'Rau các loại, cà chua, cá hồi',
      category: 'Salad',
      price: 45.000,
      countInStock: 7,
      rating: 5,
      numReviews: 24,
      mon_an_kem: [],
    },
    {
      _id: 'salad05',
      name: 'Salad thịt',
      image: '/images/salad05.png',
      ingredients:
        'Rau các loại, cà chua, sốt Mayonaise, thịt, yến mạch, đậu phụ',
      category: 'Salad',
      price: 70.000,
      countInStock: 4,
      rating: 4.5,
      numReviews: 12,
      mon_an_kem: [],
    },

    /*----------------------------*/
    {
      _id: 'sushi01',
      name: '"Một ổ" sushi',
      image: '/images/sushi01.png',
      ingredients:
        'Rong biển, cơm giấm, cá hồi, trứng cá hồi, trứng cuộn, tôm, mực, xúc xích tôm',
      category: 'Sushi',
      price: 345.000,
      countInStock: 7,
      rating: 5,
      numReviews: 32,
      mon_an_kem: ["Gừng", "wasabi", "súp miso"],
    },
    {
      _id: 'sushi02',
      name: 'Sushi calphel',
      image: '/images/sushi02.png',
      ingredients:
        'Rong biển, cơm giấm, cá hồi, trứng cá hồi, trứng cuộn, bơ',
      category: 'Sushi',
      price: 245.000,
      countInStock: 3,
      rating: 4.5,
      numReviews: 12,
      mon_an_kem: ["Gừng", "wasabi", "súp miso"],
    },
    {
      _id: 'sushi03',
      name: 'Makisushi',
      image: '/images/sushi03.png',
      ingredients:
        'Rong biển, cơm giấm, cá hồi, trứng cá hồi, trứng cuộn',
      category: 'Sushi',
      price: 225.000,
      countInStock: 3,
      rating: 5,
      numReviews: 34,
      mon_an_kem: ["Gừng", "wasabi", "súp miso"],
    },

    /*-----------------------*/
    {
      _id: 'mi01',
      name: 'Mì Ý sốt thịt bằm',
      image: '/images/mi01.png',
      ingredients:
        'Mì Ý, thịt băm',
      category: 'ndl',
      price: 36.000,
      countInStock: 3,
      rating: 5,
      numReviews: 34,
      mon_an_kem: [],
    },
    
    {
      _id: 'mi02',
      name: 'Mì xào tôm đậu',
      image: '/images/mi02.png',
      ingredients:
        'Mì, tôm, đậu Hà Lan',
      category: 'ndl',
      price: 45.000,
      countInStock: 3,
      rating: 4.5,
      numReviews: 25,
      mon_an_kem: [],
    },
    {
      _id: 'mi03',
      name: 'Mì xào tôm chả',
      image: '/images/mi03.png',
      ingredients:
        'Mì, tôm, chả cá',
      category: 'ndl',
      price: 40.000,
      countInStock: 3,
      rating: 4.5,
      numReviews: 10,
      mon_an_kem: [],
    },
    {
      _id: 'mi04',
      name: 'Mì xào rau củ',
      image: '/images/mi04.png',
      ingredients:
        'Mì, rau củ các loại',
      category: 'ndl',
      price: 45.000,
      countInStock: 8,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'mi05',
      name: 'Mì Ý sốt rượu vang',
      image: '/images/mi05.png',
      ingredients:
        'Mì Ý, sốt rượu vang',
      category: 'ndl',
      price: 50.000,
      countInStock: 4,
      rating: 3.5,
      numReviews: 17,
      mon_an_kem: [],
    },
    {
      _id: 'mi06',
      name: 'Mì Ý Alfredo',
      image: '/images/mi06.png',
      ingredients:
        'Mì Ý, cà chua, phô mai mozzarella',
      category: 'ndl',
      price: 55.000,
      countInStock: 6,
      rating: 4.5,
      numReviews: 16,
      mon_an_kem: [],
    },
    {
      _id: 'mi07',
      name: 'Pasta nui',
      image: '/images/mi07.png',
      ingredients:
        'Nui, sốt thịt băm',
      category: 'ndl',
      price: 50.000,
      countInStock: 22,
      rating: 5,
      numReviews: 67,
      mon_an_kem: [],
    },
    {
      _id: 'mi08',
      name: 'Mì pad Thái',
      image: '/images/mi08.png',
      ingredients:
        'Mì, rau củ các loại, tôm',
      category: 'ndl',
      price: 40.000,
      countInStock: 4,
      rating: 3.5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'mi09',
      name: 'Mì phô mai Mozzarella',
      image: '/images/mi09.png',
      ingredients:
        'Mì, phô mai mozzarella, xúc xích',
      category: 'ndl',
      price: 40.000,
      countInStock: 8,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },

    /*------------------------------------*/
    {
      _id: 'beefsteak01',
      name: 'Beefsteak khoai tây',
      image: '/images/beefsteak01.png',
      ingredients:
        'Bò Kobe, khoai tây',
      category: 'Beefsteak',
      price: 440.000,
      countInStock: 8,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'beefsteak02',
      name: 'Beefsteak salad',
      image: '/images/beefsteak02.png',
      ingredients:
        'Bò Kobe, salad rau trộn',
      category: 'Beefsteak',
      price: 450.000,
      countInStock: 22,
      rating: 5,
      numReviews: 67,
      mon_an_kem: ["Khoai tây"],
    },
    {
      _id: 'beefsteak03',
      name: 'Beefsteak kobe',
      image: '/images/beefsteak03.png',
      ingredients:
        'Bò Kobe',
      category: 'Beefsteak',
      price: 550.000,
      countInStock: 4,
      rating: 3.5,
      numReviews: 12,
      mon_an_kem: ["Khoai tây", "salad"],
    },

    /*------------------------*/
    {
      _id: 'ak01',
      name: 'Kimchi carrot',
      image: '/images/ak01.png',
      ingredients:
        'Củ cải đỏ',
      category: 'sub',
      price: 30.000,
      countInStock: 4,
      rating: 5,
      numReviews: 12,
      mon_an_kem: [],
    },
    {
      _id: 'ak02',
      name: 'Súp Miso',
      image: '/images/ak02.png',
      ingredients:
        'Nấm đông cô, đậu phụ',
      category: 'sub',
      price: 35.000,
      countInStock: 2,
      rating: 5,
      numReviews: 32,
      mon_an_kem: [],
    },

    /*-------------------------*/
    {
      _id: 'tiny01',
      name: 'Tiny barbecue',
      image: '/images/ak02.png',
      ingredients:
        'Thịt xiên, ớt chuông, khoai tây, rau củ các loại',
      category: 'sub2',
      price: 350.000,
      countInStock: 2,
      rating: 5,
      numReviews: 32,
      mon_an_kem: [],
    },

  ]
  
  export default dishes